name: code review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT CodeReviewer
        uses: anc95/ChatGPT-CodeReview@v1.0.3
        env:
          GITHUB_TOKEN: ${{secrets.G_TOKEN}}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Chinese

